### PR TITLE
readme: RxROS has been released

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@henrik7264: the two PRs against `ros/rosdistro` were merged, so RxROS has now officially been released into ROS Kinetic and ROS Melodic.

With that we can update the installation instructions, as building from source is no longer needed (for the non-rxros-developer install anyway).

Untill the next sync (of both Kinetic and Melodic), I'll keep this PR as a draft.

**Comment by gavanderhoorn** [comment]
We should also update the instructions (and `.rosinstall` file) of the examples repository.

**Comment by wasowski** [comment]
When is the next sync @gavanderhoorn  (just checked that the installation does not work yet for melodic).

**Comment by gavanderhoorn** [comment]
> When is the next sync @gavanderhoorn

Last sync was almost 3 weeks ago ([this one](https://discourse.ros.org/t/preparing-for-melodic-sync-2019-09-06/10570)), so I'd expect one any day now.

> just checked that the installation does not work yet for melodic

It does actually, but you'd need to use the [staging repository](http://wiki.ros.org/TestingRepository).

See [this page](http://repositories.ros.org/status_page/ros_melodic_default.html?q=rxros) for the status of the package (the red square in each of the columns indicates that the package is not yet present in the public repositories, only in the staging one).

**Comment by wasowski** [comment]
oops I 'undrafted' it by a mis-click, and don't know how to revert ...

**Comment by gavanderhoorn** [comment]
You can't.

But it's not really a problem. We'll just not merge until the sync is out.

**Comment by gavanderhoorn** [comment]
@henrik7264: the package hasn't been synced yet, so the install instructions I updated cannot successfully be used yet.

I expect the sync to happen any day now, but just so you know: if you try to follow them now, `sudo apt install ros-melodic-rxros` will fail.

**Comment by henrik7264** [comment]
Oh sorry, i was going to make an update to the README.md file and I just wanted to avoid any merge conflicts.

Can I undo my mistake?

**Comment by gavanderhoorn** [comment]
Well, we could revert, but let's not.

The sync will be soon, and then everything will be fine.

I also don't expect hundreds of issues opened by users who are trying to install `rxros` using `apt`.

**Comment by henrik7264** [comment]
OK, thanks.

**Comment by gavanderhoorn** [comment]
Apparently the next Melodic sync will be next week Monday (from [this](https://discourse.ros.org/t/preparing-for-melodic-sync-2019-09-24/10790/3)).

**Comment by gavanderhoorn** [comment]
Kinetic sync [is out](https://discourse.ros.org/t/preparing-for-kinetic-sync-2019-09-25/10804/2).

**Comment by gavanderhoorn** [comment]
And Melodic has been synced [as well](https://discourse.ros.org/t/new-packages-for-melodic-2019-09-30/10840).

@wasowski: the installation instructions in the readme should now work for you, even without the `ros-testing` repository (if you had it enabled, you'll probably want to disable it again).

**Pull request merged**
