### PR TITLE
rosinstall: rxcpp_vendor has been released.

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

Note that this PR should only be merged *after* the next Kinetic sync (as `rxcpp_vendor` is only in [ros-testing](http://wiki.ros.org/TestingRepository) right now.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
I'll convert this into a PR (no longer a draft) after the next Kinetic sync.

**Review by henrik7264 — APPROVED** [review]
OK from here.

**Comment by gavanderhoorn** [comment]
Sync is expected [today](https://discourse.ros.org/t/preparing-for-kinetic-sync-2019-09-11/10631).

**Comment by gavanderhoorn** [comment]
The [sync is out](https://discourse.ros.org/t/new-package-for-kinetic-2019-09-13/10666).

So merging.

**Comment by gavanderhoorn** [comment]
Thanks for the review @henrik7264 :+1:

**Pull request merged**
